---
AWSTemplateFormatVersion: 2010-09-09
Description: >
    This template contains Network Access Control lists
    required by the broken tshoot exercise. 

Resources:
  APPANacl:
    Type: "AWS::EC2::NetworkAcl"
    Properties:
      Tags:
        - Key: Name
          Value: picnic-nacl-appa
      VpcId: !ImportValue picnic-vpc1
  InboundRuleAppANacl100:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref APPANacl
      RuleNumber: 100 
      Protocol: 1
      Icmp:
          Code: -1
          Type: -1
      RuleAction: deny
      Egress: false
      CidrBlock: 10.16.0.0/20
  InboundRuleAppANacl200:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref APPANacl
      RuleNumber: 200 
      Protocol: -1
      RuleAction: allow
      Egress: false
      CidrBlock: 0.0.0.0/0
  OutboundRuleAppANacl100:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref APPANacl
      RuleNumber: 100 
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: 0.0.0.0/0
  RESBNacl:
    Type: "AWS::EC2::NetworkAcl"
    Properties:
      Tags:
        - Key: Name
          Value: picnic-nacl-resb
      VpcId: !ImportValue picnic-vpc1
  OutboundRuleResBNacl100:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref RESBNacl
      RuleNumber: 100 
      Protocol: 1
      Icmp:
          Code: -1
          Type: -1
      RuleAction: deny
      Egress: true
      CidrBlock: 0.0.0.0/0
  OutboundRuleResBNacl200:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref RESBNacl
      RuleNumber: 200 
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: 0.0.0.0/0
  InboundRuleResBNacl100:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref RESBNacl
      RuleNumber: 100 
      Protocol: -1
      RuleAction: allow
      Egress: false
      CidrBlock: 0.0.0.0/0
  WEBCNacl:
    Type: "AWS::EC2::NetworkAcl"
    Properties:
      Tags:
        - Key: Name
          Value: picnic-nacl-webc
      VpcId: !ImportValue picnic-vpc1
  InboundRuleWebCNacl100:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref WEBCNacl
      RuleNumber: 100
      Protocol: 1
      Icmp:
          Code: -1
          Type: -1
      RuleAction: deny
      Egress: false
      CidrBlock: 0.0.0.0/0
  InboundRuleWebCNacl200:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref WEBCNacl
      RuleNumber: 200
      Protocol: -1
      RuleAction: allow
      Egress: false
      CidrBlock: 0.0.0.0/0
  OutboundRuleWebCNacl100:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref WEBCNacl
      RuleNumber: 100 
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: 0.0.0.0/0
  APPANetworkAclAssociation:
     Type: "AWS::EC2::SubnetNetworkAclAssociation"
     Properties:
       SubnetId: !ImportValue picnic-vpc1-subnet-appa
       NetworkAclId: !Ref APPANacl
  RESBNetworkAclAssociation:
     Type: "AWS::EC2::SubnetNetworkAclAssociation"
     Properties:
       SubnetId: !ImportValue picnic-vpc1-subnet-reservedb
       NetworkAclId: !Ref RESBNacl 
  WEBCNetworkAclAssociation:
     Type: "AWS::EC2::SubnetNetworkAclAssociation"
     Properties:
       SubnetId: !ImportValue picnic-vpc1-subnet-webc
       NetworkAclId: !Ref WEBCNacl
